// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.psa.database;

import com.psa.database.Stockdata;
import com.psa.database.StockdataDataOnDemand;
import com.psa.database.StockdataIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StockdataIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StockdataIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StockdataIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StockdataIntegrationTest: @Transactional;
    
    @Autowired
    StockdataDataOnDemand StockdataIntegrationTest.dod;
    
    @Test
    public void StockdataIntegrationTest.testCountStockdatas() {
        Assert.assertNotNull("Data on demand for 'Stockdata' failed to initialize correctly", dod.getRandomStockdata());
        long count = Stockdata.countStockdatas();
        Assert.assertTrue("Counter for 'Stockdata' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StockdataIntegrationTest.testFindStockdata() {
        Stockdata obj = dod.getRandomStockdata();
        Assert.assertNotNull("Data on demand for 'Stockdata' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Stockdata' failed to provide an identifier", id);
        obj = Stockdata.findStockdata(id);
        Assert.assertNotNull("Find method for 'Stockdata' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Stockdata' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StockdataIntegrationTest.testFindAllStockdatas() {
        Assert.assertNotNull("Data on demand for 'Stockdata' failed to initialize correctly", dod.getRandomStockdata());
        long count = Stockdata.countStockdatas();
        Assert.assertTrue("Too expensive to perform a find all test for 'Stockdata', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Stockdata> result = Stockdata.findAllStockdatas();
        Assert.assertNotNull("Find all method for 'Stockdata' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Stockdata' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StockdataIntegrationTest.testFindStockdataEntries() {
        Assert.assertNotNull("Data on demand for 'Stockdata' failed to initialize correctly", dod.getRandomStockdata());
        long count = Stockdata.countStockdatas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Stockdata> result = Stockdata.findStockdataEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Stockdata' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Stockdata' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StockdataIntegrationTest.testFlush() {
        Stockdata obj = dod.getRandomStockdata();
        Assert.assertNotNull("Data on demand for 'Stockdata' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Stockdata' failed to provide an identifier", id);
        obj = Stockdata.findStockdata(id);
        Assert.assertNotNull("Find method for 'Stockdata' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStockdata(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Stockdata' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StockdataIntegrationTest.testMergeUpdate() {
        Stockdata obj = dod.getRandomStockdata();
        Assert.assertNotNull("Data on demand for 'Stockdata' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Stockdata' failed to provide an identifier", id);
        obj = Stockdata.findStockdata(id);
        boolean modified =  dod.modifyStockdata(obj);
        Integer currentVersion = obj.getVersion();
        Stockdata merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Stockdata' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StockdataIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Stockdata' failed to initialize correctly", dod.getRandomStockdata());
        Stockdata obj = dod.getNewTransientStockdata(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Stockdata' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Stockdata' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Stockdata' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StockdataIntegrationTest.testRemove() {
        Stockdata obj = dod.getRandomStockdata();
        Assert.assertNotNull("Data on demand for 'Stockdata' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Stockdata' failed to provide an identifier", id);
        obj = Stockdata.findStockdata(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Stockdata' with identifier '" + id + "'", Stockdata.findStockdata(id));
    }
    
}
