// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.psa.database;

import com.psa.database.StockdataDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect StockdataDataOnDemand_Roo_Configurable {
    
    declare @type: StockdataDataOnDemand: @Configurable;
    
}
